apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::016274943466:role/eksctl-eksctl-demo-nodegroup-ng-c-NodeInstanceRole-PICMJEIBEWPI
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-30T09:34:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1584"
  uid: da658531-aeee-43c0-8c20-f09cd74fa87e
